// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParquePublicoAPI.Data;

namespace ParquePublicoAPI.Migrations
{
    [DbContext(typeof(ParquePublicoAPIContext))]
    partial class ParquePublicoAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ParquePublicoAPI.Models.Lugar", b =>
                {
                    b.Property<long>("LugarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<float>("PrecoLugar")
                        .HasColumnType("real");

                    b.Property<long>("RuaID")
                        .HasColumnType("bigint");

                    b.HasKey("LugarID");

                    b.HasIndex("RuaID");

                    b.ToTable("Lugar");
                });

            modelBuilder.Entity("ParquePublicoAPI.Models.Reserva", b =>
                {
                    b.Property<long>("ReservaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("datetime2");

                    b.Property<long>("LugarID")
                        .HasColumnType("bigint");

                    b.HasKey("ReservaID");

                    b.HasIndex("LugarID");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("ParquePublicoAPI.Models.Rua", b =>
                {
                    b.Property<long>("RuaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lotacao")
                        .HasColumnType("int");

                    b.Property<string>("NomeRua")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RuaID");

                    b.ToTable("Rua");
                });

            modelBuilder.Entity("ParquePublicoAPI.Models.Lugar", b =>
                {
                    b.HasOne("ParquePublicoAPI.Models.Rua", "Rua")
                        .WithMany()
                        .HasForeignKey("RuaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rua");
                });

            modelBuilder.Entity("ParquePublicoAPI.Models.Reserva", b =>
                {
                    b.HasOne("ParquePublicoAPI.Models.Lugar", "Lugar")
                        .WithMany()
                        .HasForeignKey("LugarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lugar");
                });
#pragma warning restore 612, 618
        }
    }
}
